Some minor bug fixes (Suzu)
Gakuto1112/SenkoSan pull request #18
Opened 2024-03-03 12:31 UTC by FunnyShadow

PR Introduction: https://github.com/Gakuto1112/SenkoSan/pull/15
This PR is the last PR to fix some problems with `Suzu` branching.

2024-03-03 13:53 UTC, Gakuto1112 commented
Thanks for your pull request! I will review this later. However, I'm busy for another project that has a deadline, so it may takes long time to deal with it. I will do it as soon as possible.

Some codes in Suzu are same as Senko's codes. I will resolve this pull request by merging Senko's codes if I can do it.

Thanks for your corporation!

2024-03-04 14:15 UTC, Gakuto1112 requested changes
With your changes, Figura no longer emits errors. However, the same problem that I mentioned in #15 is occurred. Can you fix this?

2024-03-04 14:15 UTC, Gakuto1112 commented on scripts/general.lua
> +
The same problem that I mentioned in #15 is occurred. Can you fix this?

2024-03-06 02:37 UTC, Gakuto1112 requested changes
I mentioned about these changes [here](https://github.com/Gakuto1112/SenkoSan/pull/15#pullrequestreview-1918626595). Please check it.

2024-10-28 13:22 UTC, FunnyShadow commented
See here: https://github.com/Gakuto1112/SenkoSan/pull/15#issuecomment-2441573578

2024-10-28 13:22 UTC, closed without merging